# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

build-alpine:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.8-alpine-3.8" ansible28/alpine38/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-alpine-3.8" ansible27/alpine38/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.8-alpine-3.9" ansible28/alpine39/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-alpine-3.9" ansible27/alpine39/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.8-alpine-3.10" ansible28/alpine310/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-alpine-3.10" ansible27/alpine310/
    - docker push "$CI_REGISTRY_IMAGE"

build-ubuntu:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.8-ubuntu-16.04" ansible28/ubuntu1604/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.8-ubuntu-18.04" ansible28/ubuntu1804/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-ubuntu-16.04" ansible27/ubuntu1604/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-ubuntu-18.04" ansible27/ubuntu1804/
    - docker push "$CI_REGISTRY_IMAGE"

build-centos:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.8-centos-7" ansible28/centos7/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-centos-7" ansible27/centos7/
    - docker push "$CI_REGISTRY_IMAGE"

build-stretch:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.8-stretch" ansible28/debian-stretch/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-stretch" ansible27/debian-stretch/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.8-stretch-slim" ansible28/debian-stretch-slim/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-stretch-slim" ansible27/debian-stretch-slim/
    - docker push "$CI_REGISTRY_IMAGE"
